---
title: "Question 3"
author: "Roudranil Das"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(scales)
# library(AICcmodavg)
```

# Q3

```{r}
data_q3 <- faithful %>% 
    as_tibble()

x <- sort(data_q3$waiting)

# hist(x, xlab = 'waiting', probability = T, col='pink', main='')

```

comparing 3 models

```{r}
# model 1

p <- length(x[x<65])/length(x)

as <- mean(x[x<65])
ass <- var(x[x<65])
s <- ass/as
a <- as/s

mu <- mean(x[x>=65])
sigma <- sd(x[x>=65])

theta_inital <- c(p, a, s, mu, sigma)

neg_log_likelihood <- function(theta, data){
    n = length(data)
    
    p = theta[1]
    a = theta[2]
    s = theta[3]
    mu = theta[4]
    sigma = theta[5]
    
    l = 0
    for (i in 1:n) {
        l = l + log(p*dgamma(data[i], shape = a, scale = s) + (1-p)*dnorm(data[i], mean = mu, sd = sigma))
    }
    return(-l)
}

fit = optim(theta_inital,
      neg_log_likelihood,
      data = x,
      control = list(maxit = 1500),
      lower = c(0, 0, 0, -Inf, 0),
      upper = c(1, Inf, Inf, Inf, Inf),
      method="L-BFGS-B")

theta_1 = fit$par
theta_1

p = theta_1[1]
a = theta_1[2]
s = theta_1[3]
mu = theta_1[4]
sigma = theta_1[5]

model_1 = p*dgamma(x, shape = a, scale = s) + (1-p)*dnorm(x, mean = mu, sd = sigma)

aic_1 <- 2*5 + 2*neg_log_likelihood(theta_1, x)

# hist(x, xlab = 'waiting', probability = T, col='pink', main='')
# lines(x, model_1)
```

```{r}
# model 2

p <- length(x[x<65])/length(x)

as_1 <- mean(x[x<65])
ass_1 <- var(x[x<65])
s_1 <- ass_1/as_1
a_1 <- as_1/s_1

as_2 <- mean(x[x>=65])
ass_2 <- var(x[x>=65])
s_2 <- ass_2/as_2
a_2 <- as_2/s_2

theta_inital <- c(p, a_1, s_1, a_2, s_2)

neg_log_likelihood <- function(theta, data){
    n <- length(data)
    
    p <- theta[1]
    a_1 <- theta[2]
    s_1 <- theta[3]
    a_2 <- theta[4]
    s_2 <- theta[5]
    
    l <- 0
    for (i in 1:n) {
        l = l + log(p*dgamma(data[i], shape = a_1, scale = s_1) + (1-p)*dgamma(data[i], shape = a_2, scale = s_2))
    }
    return(-l)
}

fit = optim(theta_inital,
      neg_log_likelihood,
      data = x,
      control = list(maxit = 1500),
      lower = c(0, 0, 0, 0, 0),
      upper = c(1, Inf, Inf, Inf, Inf),
      method="L-BFGS-B")

theta_2 <- fit$par
theta_2

p <- theta_2[1]
a_1 <- theta_2[2]
s_1 <- theta_2[3]
a_2 <- theta_2[4]
s_2 <- theta_2[5]

model_2 <- p*dgamma(x, shape = a_1, scale = s_1) + (1-p)*dgamma(x, shape = a_2, scale = s_2)

aic_2 <- 2*5 + 2*neg_log_likelihood(theta_2, x)

# hist(x, xlab = 'waiting', probability = T, col='pink', main='')
# lines(x, model_2)
```

```{r}
# model 3

p <- length(x[x<65])/length(x)

m_1 <- mean(x[x<65])
v_1 <- var(x[x<65])
sigma2_1 <- log((v_1/m_1^2) + 1)
mu_1 <- log(m_1) - sigma2_1/2

m_2 <- mean(x[x>=65])
v_2 <- var(x[x>=65])
sigma2_2 <- log((v_2/m_2^2) + 1)
mu_2 <- log(m_2) - sigma2_2/2

theta_inital <- c(p, mu_1, sqrt(sigma2_1), mu_2, sqrt(sigma2_2))

neg_log_likelihood <- function(theta, data) {
    n <- length(data)
    
    p <- theta[1]
    mu_1 <- theta[2]
    sigma_1 <- theta[3]
    mu_2 <- theta[4]
    sigma_2 <- theta[5]
    
    l <- 0
    for (i in 1:n) {
        l = l + log(p*dlnorm(data[i], meanlog = mu_1, sdlog = sigma_1) + (1-p)*dlnorm(data[i], meanlog = mu_2, sdlog = sigma_2))
    }
    
    return(-l)
}

fit = optim(theta_inital,
      neg_log_likelihood,
      data = x,
      control = list(maxit = 1500),
      lower = c(0, -Inf, 0, -Inf, 0),
      upper = c(1, Inf, Inf, Inf, Inf),
      method="L-BFGS-B")

theta_3 <- fit$par
theta_3

p <- theta_3[1]
mu_1 <- theta_3[2]
sigma_1 <- theta_3[3]
mu_2 <- theta_3[4]
sigma_2 <- theta_3[5]

model_3 <- p*dlnorm(x, meanlog = mu_1, sdlog = sigma_1) + (1-p)*dlnorm(x, meanlog = mu_2, sdlog = sigma_2)

aic_3 <- 2*5 + 2*neg_log_likelihood(theta_3, x)

# hist(x, xlab = 'waiting', probability = T, col='pink', main='')
# lines(x, model_3)
```

```{r}
hist(x, xlab = 'waiting', probability = T, col='pink', main='')
lines(x, model_1, col = "red")
lines(x, model_2, col = "blue")
lines(x, model_3, col = "green")
```

```{r}
results <- data.frame(
    models = c("Gamma + Normal", "Gamma + Gamma", "Lognormal + Lognormal"),
    AIC = c(aic_1, aic_2, aic_3)
)
results
```

Based on the AIC value of all the models, we choose the third model as it has the lowest AIC value.

The required probability $\mathbb{P}[60<\texttt{waiting}<70]$ is:
```{r}
p <- theta_3[1]
mu_1 <- theta_3[2]
sigma_1 <- theta_3[3]
mu_2 <- theta_3[4]
sigma_2 <- theta_3[5]

reqd_prob <- (p*plnorm(70, meanlog = mu_1, sdlog = sigma_1) + (1-p)*plnorm(70, meanlog = mu_2, sdlog = sigma_2)) - (p*plnorm(60, meanlog = mu_1, sdlog = sigma_1) + (1-p)*plnorm(60, meanlog = mu_2, sdlog = sigma_2))
```

Hence $\mathbb{P}[60<\texttt{waiting}<70]$ =  `r reqd_prob`






